/**
 * Herní data Milanova světa — obtížnosti, nemovitosti, vylepšení, vyznamenání.
 * Přeneseno 1:1 ze samostatné hry; čísla jsou vyladěná křivka, neupravovat od oka.
 */
import type { Lang } from "@/lib/dictionaries";

export type Bi = Record<Lang, string>;

export type Diff = { id: string; mult: number; x: string; name: Bi; desc: Bi; warn: Bi };
export type Building = { id: string; i: string; c: number; r: number; n: Bi; d: Bi };
export type ClickUp = { id: string; i: string; c: number; clicks: number; n: Bi; d: Bi };
export type GlobalUp = { id: string; i: string; c: number; props: number; m: number; n: Bi; d: Bi };
export type BuildUp = { id: string; i: string; c: number; build: string; at: number; n: Bi; d: Bi };
export type PlainUp = { id: string; i: string; c: number; since?: number; n: Bi; d: Bi };
export type AnyUp = ClickUp | GlobalUp | BuildUp | PlainUp;

/** Stav, který vyznamenání vidí. `props` = součet všech vlastněných nemovitostí
 *  (v původní hře to byla globální funkce s.props). */
export type AchStats = {
  owned: Record<string, number>;
  ups: Record<string, number>;
  clicks: number;
  totalMin: number;
  totalMoney: number;
  diff: string | null;
  props: number;
};

export type Ach = { id: string; n: Bi; d: Bi; t: (s: AchStats) => boolean };

export const DIFFS: Record<string, Diff> = {
  smrtelnik: { id:"smrtelnik", mult:1, x:"1×",
    name:{ cs:"Běžný smrtelník", en:"Ordinary mortal" },
    desc:{ cs:"Stojíš ve frontě jako každý jiný. Jedna minuta na úřadě = 1 Kč. Poctivá, dlouhá cesta k vesmíru.",
           en:"You queue like everybody else. One minute at the office = 0.05 USD. The honest, long road to the universe." },
    warn:{ cs:"Doporučeno pro první žádost", en:"Recommended for a first application" } },
  byrokrat: { id:"byrokrat", mult:3, x:"3×",
    name:{ cs:"Zkušený byrokrat", en:"Seasoned bureaucrat" },
    desc:{ cs:"Znáš formuláře, chodíš rovnou k okénku č. 3. Jedna minuta = 3 Kč, všechno roste třikrát rychleji.",
           en:"You know the forms and walk straight to window no. 3. One minute = 0.15 USD, everything grows three times faster." },
    warn:{ cs:"Pro znalce úředních hodin", en:"For connoisseurs of opening hours" } },
  milan: { id:"milan", mult:10, x:"1× → 10×",
    name:{ cs:"Na Milana", en:"Milan mode" },
    desc:{ cs:"Milan na úřadě nečeká — úřad čeká na Milana. Začínáš ale na obyčejné sazbě 1 Kč za minutu. Desetinásobek přijde, až si ho zasloužíš.",
           en:"Milan doesn't wait at the office — the office waits for Milan. You start on the ordinary rate of 0.05 USD a minute, though. The tenfold comes once you have earned it." },
    warn:{ cs:"Násobič se odemyká až ve hře", en:"The multiplier unlocks in play" } }
};

export const BUILDINGS: Building[] = [
  { id:"popelnice", i:"🗑️", c:150, r:1,
    n:{cs:"Popelnice",en:"Wheelie bin"},
    d:{cs:"Modrá, na papír, s vlastním stanovištěm. Pronajímáš ji sousedovi, který nemá kam.",
       en:"Blue, for paper, with its own designated spot. You rent it to the neighbour who has nowhere to put his."} },
  { id:"kadibudka", i:"🚻", c:500, r:2.99,
    n:{cs:"Kadibudka",en:"Outhouse"},
    d:{cs:"Dřevěná, na zahradě, bez čísla popisného. Vlastní bydlení je vlastní bydlení.",
       en:"Wooden, in the garden, no house number. Owning your own place is owning your own place."} },
  { id:"psibouda", i:"🐕", c:1500, r:8.05,
    n:{cs:"Psí bouda",en:"Doghouse"},
    d:{cs:"Zateplená, s předsíňkou. Nájemník štěká, ale platí včas.",
       en:"Insulated, with a little porch. The tenant barks, but pays on time."} },
  { id:"kulna", i:"🧰", c:6000, r:28.9,
    n:{cs:"Zahradní kůlna",en:"Garden shed"},
    d:{cs:"Pletivo, plechová střecha, tři kola bez duší. Nikdo neví, čí jsou.",
       en:"Wire fence, tin roof, three bikes with no inner tubes. Nobody knows whose they are."} },
  { id:"chatka", i:"🏕️", c:40000, r:172,
    n:{cs:"Zahrádkářská chatka",en:"Allotment hut"},
    d:{cs:"Kolonie za nádražím. Elektřina z prodlužky, voda z hydrantu.",
       en:"An allotment colony behind the station. Power from an extension lead, water from a hydrant."} },
  { id:"koje", i:"🔦", c:90000, r:348,
    n:{cs:"Sklepní kóje",en:"Cellar storage unit"},
    d:{cs:"Tři metry čtvereční, jedna žárovka, půl metráku brambor.",
       en:"Three square metres, one bulb, fifty kilos of potatoes."} },
  { id:"maringotka", i:"🚚", c:200000, r:693,
    n:{cs:"Maringotka",en:"Site caravan"},
    d:{cs:"Na kolech, takže technicky vzato movitá. Katastr se nedozví.",
       en:"On wheels, so technically movable property. The land registry will never know."} },
  { id:"garaz", i:"🚗", c:400000, r:1240,
    n:{cs:"Garáž",en:"Garage"},
    d:{cs:"Plechová, ale s elektřinou. Soused v ní bydlí už osmý rok.",
       en:"Sheet metal, but wired for power. The neighbour has been living in it for eight years."} },
  { id:"parcela", i:"📐", c:1500000, r:4180,
    n:{cs:"Stavební parcela",en:"Building plot"},
    d:{cs:"Zasíťovaná, s příjezdovkou. Územní plán ji vede jako ornou půdu.",
       en:"Serviced, with a driveway. The zoning plan still lists it as arable land."} },
  { id:"chata", i:"🌲", c:2200000, r:5500,
    n:{cs:"Chata u lesa",en:"Cabin by the woods"},
    d:{cs:"Srub, kamna, suché WC. V zimě se tam nedostaneš.",
       en:"A log cabin, a stove, a composting toilet. In winter you can't get there at all."} },
  { id:"garsonka", i:"🛏️", c:3000000, r:6720,
    n:{cs:"Garsonka 1+kk",en:"Studio flat"},
    d:{cs:"Kuchyňský kout je vlastně jen kout. Nájemník platí včas.",
       en:"The kitchenette is really just a corner. The tenant pays on time."} },
  { id:"b2kk", i:"🚿", c:4200000, r:8440,
    n:{cs:"Byt 2+kk",en:"Open-plan one-bed flat"},
    d:{cs:"Novější panel, plastová okna, sklep. Ideální investiční byt.",
       en:"A newer block, uPVC windows, a cellar. The ideal buy-to-let."} },
  { id:"b21", i:"🪑", c:5600000, r:10100,
    n:{cs:"Byt 2+1",en:"Two-room flat"},
    d:{cs:"Čtvrté patro, výtah nefunguje. Zato jádro po rekonstrukci.",
       en:"Fourth floor, the lift is out. The bathroom core is renovated, though."} },
  { id:"b31", i:"🛋️", c:7800000, r:12600,
    n:{cs:"Byt 3+1",en:"Three-room flat"},
    d:{cs:"Lodžie, sklep, komora. Rodinný standard socialistického realismu.",
       en:"A loggia, a cellar, a pantry. The family standard of socialist realism."} },
  { id:"b41", i:"🚪", c:9500000, r:13800,
    n:{cs:"Byt 4+1",en:"Four-room flat"},
    d:{cs:"Tři dětské pokoje, jedna koupelna. Ráno je to bitva.",
       en:"Three children's rooms, one bathroom. Mornings are a battle."} },
  { id:"radovka", i:"🏘️", c:12000000, r:15600,
    n:{cs:"Řadový domek",en:"Terraced house"},
    d:{cs:"Šest metrů široký, tři patra vysoký. Se sousedem sdílíš zeď i názory.",
       en:"Six metres wide, three storeys tall. You share a wall with the neighbour, and his opinions."} },
  { id:"b51", i:"🗝️", c:14000000, r:16300,
    n:{cs:"Byt 5+1",en:"Five-room flat"},
    d:{cs:"Tolik dveří, že se v něm ztratíš. Topení stojí víc než nájem.",
       en:"So many doors you get lost. Heating costs more than the rent."} },
  { id:"novostavba", i:"🏢", c:18000000, r:18800,
    n:{cs:"Byt v novostavbě",en:"New-build apartment"},
    d:{cs:"Sádrokarton, chytrá domácnost a poplatek za parkování 3 000 měsíčně.",
       en:"Plasterboard, a smart home and a parking fee of 3,000 a month."} },
  { id:"dum", i:"🏡", c:25000000, r:23400,
    n:{cs:"Rodinný dům",en:"Family house"},
    d:{cs:"Zahrada, kůlna, hypotéka na třicet let. Klasika.",
       en:"A garden, a shed, a thirty-year mortgage. The classic."} },
  { id:"vila", i:"🏖️", c:60000000, r:50400,
    n:{cs:"Vila s bazénem",en:"Villa with a pool"},
    d:{cs:"Bazén se čistí sám, plot je vysoký, sousedi nejsou.",
       en:"The pool cleans itself, the fence is high, there are no neighbours."} },
  { id:"zamek", i:"🏯", c:120000000, r:90400,
    n:{cs:"Zámek",en:"Chateau"},
    d:{cs:"Barokní, památkově chráněný. Na každé okno je potřeba jiné razítko.",
       en:"Baroque, listed. Every single window needs a different stamp."} },
  { id:"cinzak", i:"🏚️", c:200000000, r:135000,
    n:{cs:"Činžovní dům",en:"Tenement building"},
    d:{cs:"Secesní, v centru, dvacet nájemníků. Osmnáct z nich má regulovaný nájem.",
       en:"Art nouveau, city centre, twenty tenants. Eighteen of them on regulated rent."} },
  { id:"hrad", i:"🏰", c:450000000, r:272000,
    n:{cs:"Hrad",en:"Castle"},
    d:{cs:"Kamenný, s příkopem. Duch v západním křídle platí nepravidelně.",
       en:"Stone, with a moat. The ghost in the west wing pays irregularly."} },
  { id:"panelak", i:"🏬", c:700000000, r:380000,
    n:{cs:"Celý panelák",en:"An entire tower block"},
    d:{cs:"Osmdesát bytů, jeden výtah a společenství vlastníků, které tě nenávidí.",
       en:"Eighty flats, one lift and an owners' association that hates you."} },
  { id:"kancelar", i:"🏤", c:2000000000, r:974000,
    n:{cs:"Kancelářská budova",en:"Office building"},
    d:{cs:"Třída A, open space, kávovar v každém patře. Obsazenost 40 %.",
       en:"Class A, open plan, a coffee machine on every floor. Occupancy 40 %."} },
  { id:"nakupak", i:"🛒", c:8000000000, r:3490000,
    n:{cs:"Nákupní centrum",en:"Shopping mall"},
    d:{cs:"Sto padesát obchodů, food court, parkoviště pro tisíc aut.",
       en:"A hundred and fifty shops, a food court, parking for a thousand cars."} },
  { id:"katastr", i:"🗄️", c:30000000000, r:11800000,
    n:{cs:"Katastrální úřad",en:"The land registry"},
    d:{cs:"Teď už si zápisy do katastru schvaluješ sám. Fronta je pořád stejná.",
       en:"Now you approve your own entries. The queue is exactly as long as before."} },
  { id:"magistrat", i:"🏛️", c:150000000000, r:52600000,
    n:{cs:"Magistrát",en:"City hall"},
    d:{cs:"Devět odborů, čtyři patra, jedna kantýna. Úřední hodiny určuješ ty.",
       en:"Nine departments, four floors, one canteen. You set the opening hours."} },
  { id:"letiste", i:"✈️", c:800000000000, r:252000000,
    n:{cs:"Mezinárodní letiště",en:"International airport"},
    d:{cs:"Dvě dráhy, tři terminály a celnice, která ti teď taky patří.",
       en:"Two runways, three terminals and a customs office that is now yours as well."} },
  { id:"mesto", i:"🌆", c:5000000000000, r:1410000000,
    n:{cs:"Celé město",en:"The whole city"},
    d:{cs:"Náměstí, kanalizace, parkovací zóny. Vybíráš daň z nemovitosti sám sobě.",
       en:"A square, sewers, parking zones. You collect property tax from yourself."} },
  { id:"kraj", i:"🗺️", c:60000000000000, r:15200000000,
    n:{cs:"Celý kraj",en:"The whole region"},
    d:{cs:"Čtrnáct okresů, dvě nemocnice a jedna nedostavěná dálnice.",
       en:"Fourteen districts, two hospitals and one unfinished motorway."} },
  { id:"zeme", i:"🚩", c:800000000000000, r:182000000000,
    n:{cs:"Celá země",en:"The whole country"},
    d:{cs:"Všechny nemovitosti v katastru země. Včetně těch, co nikdo nezaplatil.",
       en:"Every property in the national registry. Including the ones nobody ever paid for."} },
  { id:"kontinent", i:"🌍", c:1.2e16, r:2440000000000,
    n:{cs:"Celý kontinent",en:"The whole continent"},
    d:{cs:"Od Lisabonu po Ural. Přeshraniční řízení trvá o něco déle.",
       en:"From Lisbon to the Urals. Cross-border proceedings take a little longer."} },
  { id:"svet", i:"🌐", c:2e17, r:36400000000000,
    n:{cs:"Celý svět",en:"The whole world"},
    d:{cs:"Souš i oceány. Dno se eviduje zvlášť, na to je jiný formulář.",
       en:"Land and oceans. The seabed is filed separately, on a different form."} },
  { id:"orbita", i:"🛰️", c:4e18, r:653000000000000,
    n:{cs:"Orbitální stanice",en:"Orbital station"},
    d:{cs:"Nájem se platí v kyslíku. Výhled je ovšem bez konkurence.",
       en:"Rent is paid in oxygen. The view, however, is unbeatable."} },
  { id:"mesic", i:"🌕", c:8e19, r:1.17e16,
    n:{cs:"Měsíc",en:"The Moon"},
    d:{cs:"Bez atmosféry, zato s výhledem. Kolonizace zatím v územním řízení.",
       en:"No atmosphere, but quite a view. Colonisation is still in planning permission."} },
  { id:"mars", i:"🔴", c:2e21, r:2.62e17,
    n:{cs:"Mars",en:"Mars"},
    d:{cs:"Rezavý, prašný, levný. Voda v ceně, kyslík za příplatek.",
       en:"Rusty, dusty, cheap. Water included, oxygen at extra cost."} },
  { id:"asteroidy", i:"☄️", c:5e22, r:5.87e18,
    n:{cs:"Pás asteroidů",en:"The asteroid belt"},
    d:{cs:"Milion parcel, žádné dvě stejné. Geometrický plán je noční můra.",
       en:"A million plots, no two alike. The survey drawing is a nightmare."} },
  { id:"soustava", i:"☀️", c:1.5e24, r:1.58e20,
    n:{cs:"Sluneční soustava",en:"The Solar System"},
    d:{cs:"Osm planet, jedna hvězda, spousta neevidovaných asteroidů.",
       en:"Eight planets, one star, a great many unregistered asteroids."} },
  { id:"galaxie", i:"🌌", c:5e25, r:4.72e21,
    n:{cs:"Galaxie",en:"The galaxy"},
    d:{cs:"Sto miliard hvězd. Odhad ceny provedl znalec od oka.",
       en:"A hundred billion stars. The valuation was done by eye."} },
  { id:"kupa", i:"🕸️", c:2e27, r:1.69e23,
    n:{cs:"Kupa galaxií",en:"A galaxy cluster"},
    d:{cs:"Tisíc galaxií na jedné parcele. Vlastnická hranice se rozpíná.",
       en:"A thousand galaxies on a single plot. The boundary line keeps expanding."} },
  { id:"vesmir", i:"🪐", c:1e29, r:7.68e24,
    n:{cs:"Milanův vesmír",en:"Milan's universe"},
    d:{cs:"Všechno, co je. Vklad do katastru zapsán s právními účinky k počátku času.",
       en:"Everything that is. Entered in the registry with legal effect from the beginning of time."} }
];
export const GROWTH = 1.15;

export const CLICK_UPS: ClickUp[] = [
  { id:"c1", i:"🖊️", c:300, clicks:15,
    n:{cs:"Propiska na řetízku",en:"Pen on a chain"},
    d:{cs:"Konečně píšeš vlastní propiskou. Úřednice se tváří dotčeně.",
       en:"At last you write with your own pen. The clerk looks offended."} },
  { id:"c2", i:"🔖", c:2000, clicks:50,
    n:{cs:"Vlastní razítko",en:"Your own rubber stamp"},
    d:{cs:"Doma vyrobené, ale kulaté. Nikdo se neptá.",
       en:"Homemade, but round. Nobody asks questions."} },
  { id:"c3", i:"🎫", c:15000, clicks:120,
    n:{cs:"Kolek za 100 Kč",en:"A 100-crown duty stamp"},
    d:{cs:"Nalepený nakřivo, ale platný. Podání se okamžitě zrychluje.",
       en:"Stuck on crooked, but valid. Filings speed up immediately."} },
  { id:"c4", i:"📬", c:120000, clicks:250,
    n:{cs:"Datová schránka",en:"Government data mailbox"},
    d:{cs:"Doručeno fikcí desátý den. Zákon je zákon.",
       en:"Deemed delivered on the tenth day. The law is the law."} },
  { id:"c5", i:"📜", c:1500000, clicks:500,
    n:{cs:"Plná moc",en:"Power of attorney"},
    d:{cs:"Stojíš ve dvou frontách naráz. Fyzika si stěžovala, marně.",
       en:"You queue in two lines at once. Physics complained, in vain."} },
  { id:"c6", i:"✍️", c:2e7, clicks:900,
    n:{cs:"Ověřený podpis",en:"Notarised signature"},
    d:{cs:"Notář si účtoval víc než pořizovací cena kadibudky.",
       en:"The notary charged more than the outhouse cost."} },
  { id:"c7", i:"☕", c:3e8, clicks:1600,
    n:{cs:"Známá na okénku č. 3",en:"A friend at window no. 3"},
    d:{cs:"Nosíš jí kafe, ona ti nosí razítka mimo pořadí.",
       en:"You bring her coffee, she brings you stamps out of turn."} },
  { id:"c8", i:"⚖️", c:5e9, clicks:2800,
    n:{cs:"Advokátní kancelář",en:"Law firm"},
    d:{cs:"Tři koncipienti, jeden partner, hodinová sazba jako nájem 3+1.",
       en:"Three trainees, one partner, an hourly rate the size of a family flat's rent."} },
  { id:"c9", i:"🤝", c:1e11, clicks:4500,
    n:{cs:"Lobbista",en:"Lobbyist"},
    d:{cs:"Nikdy ho nevidíš, ale lhůty se zkracují samy.",
       en:"You never see him, but deadlines shorten by themselves."} },
  { id:"c10", i:"🎩", c:3e12, clicks:7000,
    n:{cs:"Ministr pro místní rozvoj",en:"Minister for Regional Development"},
    d:{cs:"Bere ti telefon. Někdy i o víkendu.",
       en:"He takes your calls. Sometimes even at weekends."} },
  { id:"c11", i:"📕", c:1e15, clicks:12000,
    n:{cs:"Vlastní zákon",en:"A law of your own"},
    d:{cs:"Vyšlo ve sbírce, účinnost dnem podpisu. Zkráceně: lex Ty.",
       en:"Published in the statute book, effective on signature. Known as lex You."} },
  { id:"c12", i:"🧠", c:5e18, clicks:25000,
    n:{cs:"Přepis katastru myšlenkou",en:"Rewriting the registry by thought"},
    d:{cs:"Stačí si to představit a v katastru je to zapsané.",
       en:"You picture it and it is entered in the registry."} },
  { id:"c13", i:"⏳", c:1e23, clicks:50000,
    n:{cs:"Zrušení pojmu času",en:"Abolishing the concept of time"},
    d:{cs:"Minuta trvá, jak dlouho potřebuješ. Fronta zmizela sama.",
       en:"A minute lasts as long as you need. The queue vanished on its own."} }
];

export const GLOBAL_UPS: GlobalUp[] = [
  { id:"g1", i:"💾", c:5e7, props:40, m:1.5,
    n:{cs:"Elektronizace úřadu",en:"Digitising the office"},
    d:{cs:"Formuláře jsou teď v PDF, které se nedá vyplnit. Přesto je to rychlejší.",
       en:"The forms are now PDFs you cannot fill in. It is faster all the same."} },
  { id:"g2", i:"🕗", c:5e10, props:100, m:1.5,
    n:{cs:"Zrušení úředních hodin",en:"Abolishing opening hours"},
    d:{cs:"Otevřeno pořád. Úterý a čtvrtek už nejsou svaté.",
       en:"Always open. Tuesdays and Thursdays are no longer sacred."} },
  { id:"g3", i:"🏦", c:1e14, props:200, m:2,
    n:{cs:"Jednotné inkasní místo",en:"Single collection point"},
    d:{cs:"Jeden formulář místo devíti. Trvalo to jen dvacet let.",
       en:"One form instead of nine. It only took twenty years."} },
  { id:"g4", i:"📐", c:1e18, props:350, m:2,
    n:{cs:"Digitální stavební řízení",en:"Digital building permits"},
    d:{cs:"Funguje. Vážně. Sami tomu nevěří.",
       en:"It works. Really. They can't believe it themselves."} },
  { id:"g5", i:"🧨", c:1e22, props:500, m:2.5,
    n:{cs:"Zrušení stavebního zákona",en:"Repealing the building act"},
    d:{cs:"Stavíš, kde chceš. Chaos, ale svobodný.",
       en:"You build wherever you like. Chaos, but a free one."} },
  { id:"g6", i:"🛰️", c:1e27, props:800, m:3,
    n:{cs:"Vesmírný katastr",en:"Cosmic land registry"},
    d:{cs:"Parcelní čísla mají devatenáct míst a vlastní časové pásmo.",
       en:"Plot numbers have nineteen digits and a time zone of their own."} }
];

export const BUILD_TIERS: { at: number; mult: number; pre: Bi }[] = [
  { at:10,  mult:100,   pre:{cs:"Rekonstrukce",en:"Renovation"} },
  { at:25,  mult:2500,  pre:{cs:"Kolaudace",en:"Final inspection"} },
  { at:50,  mult:80000, pre:{cs:"Developerský projekt",en:"Development project"} },
  { at:100, mult:3e6,   pre:{cs:"Územní plán",en:"Zoning plan"} },
  { at:200, mult:2e8,   pre:{cs:"Monopol na",en:"Monopoly on"} }
];
export const BUILD_UPS: BuildUp[] = [];
BUILDINGS.forEach((b) => {
  BUILD_TIERS.forEach((tier, ti) => {
    BUILD_UPS.push({
      id: b.id + "_t" + ti, i: b.i, c: b.c * tier.mult, build: b.id, at: tier.at,
      n: { cs: tier.pre.cs + ": " + b.n.cs, en: tier.pre.en + ": " + b.n.en },
      d: { cs: b.n.cs + " vynáší dvojnásobek. Papírování narostlo úměrně.",
           en: b.n.en + " yields twice as much. The paperwork grew accordingly." }
    });
  });
});


export const FIRMA: PlainUp = { id:"f0", i:"📈", c:4000000, since:3000000,
  n:{cs:"Podíl ve firmě",en:"A stake in a company"},
  d:{cs:"Z toho jednou bude 150 milionů.",en:"One day this will be worth 7.5 million."} };


export const MARRY: PlainUp = { id:"m0", i:"💍", c:0,
  n:{cs:"Dobré se oženit",en:"Marrying well"},
  d:{cs:"Milan se oženil. Od té chvíle mu úřady chodí naproti, fronty se rozestupují a každá promarněná minuta vynáší desetkrát víc.",
     en:"Milan got married. From that moment the offices meet him halfway, the queues part, and every wasted minute pays ten times more."} };


export const ACHS: Ach[] = [
  { id:"a1", n:{cs:"První kolek",en:"The first duty stamp"},
    d:{cs:"Kup kadibudku.",en:"Buy the outhouse."}, t:function(s: AchStats){ return (s.owned.kadibudka||0) >= 1; } },
  { id:"a2", n:{cs:"Drobný pronajímatel",en:"Small-time landlord"},
    d:{cs:"Vlastni 10 nemovitostí.",en:"Own 10 properties."}, t:function(s: AchStats){ return s.props >= 10; } },
  { id:"a3", n:{cs:"Realitní kancelář",en:"Estate agency"},
    d:{cs:"Vlastni 100 nemovitostí.",en:"Own 100 properties."}, t:function(s: AchStats){ return s.props >= 100; } },
  { id:"a4", n:{cs:"Developer",en:"Developer"},
    d:{cs:"Vlastni 500 nemovitostí.",en:"Own 500 properties."}, t:function(s: AchStats){ return s.props >= 500; } },
  { id:"a5", n:{cs:"Přišel jste na špatné okénko",en:"Wrong window, sir"},
    d:{cs:"Naklikej 100 razítek.",en:"Click 100 stamps."}, t:function(s: AchStats){ return s.clicks >= 100; } },
  { id:"a6", n:{cs:"Otlačený palec",en:"Bruised thumb"},
    d:{cs:"Naklikej 5 000 razítek.",en:"Click 5,000 stamps."}, t:function(s: AchStats){ return s.clicks >= 5000; } },
  { id:"a7", n:{cs:"Ve frontě",en:"In the queue"},
    d:{cs:"Nasbírej 10 000 minut.",en:"Collect 10,000 minutes."}, t:function(s: AchStats){ return s.totalMin >= 10000; } },
  { id:"a8", n:{cs:"Půl života na úřadě",en:"Half a life at the office"},
    d:{cs:"Nasbírej milion minut.",en:"Collect a million minutes."}, t:function(s: AchStats){ return s.totalMin >= 1e6; } },
  { id:"a9", n:{cs:"Věčnost v čekárně",en:"An eternity in the waiting room"},
    d:{cs:"Nasbírej miliardu minut.",en:"Collect a billion minutes."}, t:function(s: AchStats){ return s.totalMin >= 1e9; } },
  { id:"a10", n:{cs:"Milionář",en:"Fifty grand"},
    d:{cs:"Vydělej celkem milion Kč.",en:"Earn 50,000 USD in total."}, t:function(s: AchStats){ return s.totalMoney >= 1e6; } },
  { id:"a11", n:{cs:"Miliardář",en:"Fifty million"},
    d:{cs:"Vydělej celkem miliardu Kč.",en:"Earn 50 million USD in total."}, t:function(s: AchStats){ return s.totalMoney >= 1e9; } },
  { id:"a12", n:{cs:"Panstvo",en:"Landed gentry"},
    d:{cs:"Kup zámek.",en:"Buy the chateau."}, t:function(s: AchStats){ return (s.owned.zamek||0) >= 1; } },
  { id:"a13", n:{cs:"Feudál",en:"Feudal lord"},
    d:{cs:"Kup hrad.",en:"Buy the castle."}, t:function(s: AchStats){ return (s.owned.hrad||0) >= 1; } },
  { id:"a14", n:{cs:"Úředníkem sobě",en:"Your own clerk"},
    d:{cs:"Kup katastrální úřad.",en:"Buy the land registry."}, t:function(s: AchStats){ return (s.owned.katastr||0) >= 1; } },
  { id:"a15", n:{cs:"Pan starosta",en:"Mr Mayor"},
    d:{cs:"Kup celé město.",en:"Buy the whole city."}, t:function(s: AchStats){ return (s.owned.mesto||0) >= 1; } },
  { id:"a16", n:{cs:"Hlava státu",en:"Head of state"},
    d:{cs:"Kup celou zemi.",en:"Buy the whole country."}, t:function(s: AchStats){ return (s.owned.zeme||0) >= 1; } },
  { id:"a17", n:{cs:"Kosmonaut",en:"Cosmonaut"},
    d:{cs:"Kup Měsíc.",en:"Buy the Moon."}, t:function(s: AchStats){ return (s.owned.mesic||0) >= 1; } },
  { id:"a18", n:{cs:"Papírování",en:"Paperwork"},
    d:{cs:"Kup 25 vylepšení.",en:"Buy 25 upgrades."}, t:function(s: AchStats){ return Object.keys(s.ups).length >= 25; } },
  { id:"a19", n:{cs:"Na Milana",en:"Milan mode"},
    d:{cs:"Hraj v kategorii Na Milana.",en:"Play in the Milan category."}, t:function(s: AchStats){ return s.diff === "milan"; } },
  { id:"a20", n:{cs:"Vlastník všeho",en:"Owner of everything"},
    d:{cs:"Kup Milanův vesmír.",en:"Buy Milan's universe."}, t:function(s: AchStats){ return (s.owned.vesmir||0) >= 1; } }
];
