// Pixel-art ikony jako SVG mřížka čtverečků. '.' = průhledné.

const P = {
  k: "#1a1614", w: "#ffffff", y: "#ffd23f", o: "#ff8c1a", r: "#e23b3b",
  p: "#ff6fae", b: "#4aa3ff", c: "#5fd0d8", g: "#5ec46a", v: "#9b6cff",
  n: "#9aa0ab", d: "#b97a3a", s: "#ffe9b0", e: "#2e7d4f",
} as const;

type IconDef = { rows: string[] };

const ICONS: Record<string, IconDef> = {
  dino: { rows: [
    "........gg",
    ".......ggg",
    "......gggg",
    "g.....gkgg",
    "gg..gggggg",
    "gggggggggg",
    ".gggggggg.",
    ".gg.gg.gg.",
    ".g..g..g..",
    "..........",
  ] },
  column: { rows: [
    "..........",
    ".nnnnnnnn.",
    "..nnnnnn..",
    "...n..n...",
    "...n..n...",
    "...n..n...",
    "...n..n...",
    "...n..n...",
    "..nnnnnn..",
    ".nnnnnnnn.",
  ] },
  wizard: { rows: [
    "....v.....",
    "...vv.....",
    "...vvw....",
    "..vvvvv...",
    "..vvvvv...",
    ".vvvvvvv..",
    "vvvvvvvvv.",
    ".kkkkkkk..",
    "..........",
    "..........",
  ] },
  rocket: { rows: [
    "....w.....",
    "...www....",
    "...wrw....",
    "...wrw....",
    "...www....",
    "..wwwww...",
    ".w..w..w..",
    "r..www..r.",
    "....o.....",
    "...ooo....",
  ] },
  wave: { rows: [
    "..........",
    "....cc....",
    "..cc..cc..",
    ".c.b..b.c.",
    "cbbbbbbbbc",
    "bbbbbbbbbb",
    ".bbbbbbbb.",
    "..bbbbbb..",
    "..........",
    "..........",
  ] },
  bubble: { rows: [
    "..........",
    "...cccc...",
    "..c....c..",
    ".c.w....c.",
    ".c......c.",
    ".c......c.",
    ".c......c.",
    "..c....c..",
    "...cccc...",
    "..........",
  ] },
  coffee: { rows: [
    "..........",
    "...ss.....",
    "..ss......",
    ".kkkkkk.k.",
    ".kddddk.kk",
    ".kddddk.k.",
    ".kddddkk..",
    ".k....k...",
    "..kkkk....",
    "..........",
  ] },
  spiral: { rows: [
    "...vvvv...",
    "..v....v..",
    ".v..vvv.v.",
    ".v.v...v..",
    ".v.v.vvv..",
    ".v.v......",
    ".v..vvvv..",
    "..v.....v.",
    "...vvvvv..",
    "..........",
  ] },
  skull: { rows: [
    "..wwwww...",
    ".wwwwwww..",
    ".wkwwkww..",
    ".wwwwwww..",
    ".wwkwwww..",
    ".wwwwwww..",
    "..wwwww...",
    "..w.w.w...",
    "..........",
    "..........",
  ] },
  pizza: { rows: [
    "....y.....",
    "...yyy....",
    "...yry....",
    "..yyyyy...",
    "..yryyr...",
    ".yyyyyyy..",
    ".yyryyyy..",
    "dddddddddd",
    "..........",
    "..........",
  ] },
  duck: { rows: [
    "..........",
    ".....yy...",
    "....yyyy..",
    "....yyky..",
    "..ooyyyy..",
    "....yyyy..",
    "..yyyyyyy.",
    ".yyyyyyyy.",
    ".yyyyyyy..",
    "..yyyy....",
  ] },
  bolt: { rows: [
    "....yy....",
    "...yy.....",
    "..yy......",
    ".yyyy.....",
    "...yyy....",
    "....yy....",
    "...yy.....",
    "..yy......",
    ".y........",
    "..........",
  ] },
  hole: { rows: [
    "..........",
    "..vvvvv...",
    ".vkkkkkv..",
    "vkkkkkkkv.",
    "vkkkkkkkv.",
    "vkkkkkkkv.",
    ".vkkkkkv..",
    "..vvvvv...",
    "..........",
    "..........",
  ] },
  sparkle: { rows: [
    "....y.....",
    "....y.....",
    "..y.y.y...",
    "...yyy....",
    "yyyyyyyyy.",
    "...yyy....",
    "..y.y.y...",
    "....y.....",
    "....y.....",
    "..........",
  ] },
  ice: { rows: [
    "..........",
    "..cccccc..",
    ".cwc....c.",
    ".cc.....c.",
    ".c......c.",
    ".c......c.",
    ".c......c.",
    ".c......c.",
    "..cccccc..",
    "..........",
  ] },
  chart: { rows: [
    "..........",
    ".......c..",
    "...b...c..",
    "...b.g.c..",
    "...b.g.c..",
    ".y.b.g.c..",
    ".y.b.g.c..",
    ".y.b.g.c..",
    "kkkkkkkkk.",
    "..........",
  ] },
  phone: { rows: [
    "..kkkkk...",
    ".kkkkkkk..",
    ".kwwwwwk..",
    ".kwwwwwk..",
    ".kwwwwwk..",
    ".kwwwwwk..",
    ".kwwwwwk..",
    ".kkkkkkk..",
    ".kk.k.kk..",
    "..kkkkk...",
  ] },
  rainbow: { rows: [
    "...rrrr...",
    "..r....r..",
    ".r.yyyy.r.",
    "r.y....y.r",
    ".y.gggg.y.",
    "y.g....g.y",
    "..g.bb.g..",
    "...b..b...",
    "..........",
    "..........",
  ] },
  wrench: { rows: [
    ".nn.......",
    "nnnn......",
    "nn.nn.....",
    ".nnnn.....",
    "..nnn.....",
    "...nnn....",
    "....nnn...",
    ".....nnn..",
    "......nnnn",
    ".......nn.",
  ] },
  mail: { rows: [
    "..........",
    ".kkkkkkkk.",
    ".kwwwwwwk.",
    ".kwk..kwk.",
    ".kw.kk.wk.",
    ".kwk..kwk.",
    ".kwwwwwwk.",
    ".kkkkkkkk.",
    "..........",
    "..........",
  ] },
  butterfly: { rows: [
    "pp...k...p",
    "pppp.k.ppp",
    "ppppvkvppp",
    "ppppvkvppp",
    ".ppp.k.pp.",
    "..pp.k.p..",
    "...p.k.p..",
    "..........",
    "..........",
    "..........",
  ] },
  robot: { rows: [
    "..k...k...",
    "..k...k...",
    ".kkkkkkk..",
    ".kccccck..",
    ".kckckck..",
    ".kccccck..",
    ".kckkkck..",
    ".kccccck..",
    ".kkkkkkk..",
    "..k...k...",
  ] },
  sleep: { rows: [
    "......zzz.",
    ".....z....",
    "...ww.z...",
    "..w..wzzz.",
    "..w.......",
    "..w..w....",
    "...ww.....",
    "..........",
    "..........",
    "..........",
  ] },
  mirror: { rows: [
    "...kkkk...",
    "..kbbbbk..",
    ".kbbbbbbk.",
    ".kbbbbbbk.",
    ".kbbbbbbk.",
    "..kbbbbk..",
    "...kkkk...",
    "....kk....",
    "....kk....",
    "...kkkk...",
  ] },
  mute: { rows: [
    "..........",
    "..yyyyy...",
    ".yyyyyyy..",
    ".ykyyykyy.",
    ".yyyyyyy..",
    ".yyyyyyy..",
    ".yyyyyyy..",
    "..yyyyy...",
    "..........",
    "..........",
  ] },
  infinity: { rows: [
    "..........",
    "..........",
    ".vv...vv..",
    "v..v.v..v.",
    "v..v.v..v.",
    "v..v.v..v.",
    ".vv...vv..",
    "..........",
    "..........",
    "..........",
  ] },
  clock: { rows: [
    "...k.k....",
    "..kkkkk...",
    ".kwwwwwk..",
    ".kwwkwwk..",
    ".kwwkwwk..",
    ".kwwkkwk..",
    ".kwwwwwk..",
    "..kkkkk...",
    "..k...k...",
    "..k...k...",
  ] },
};

const ICON_FOR: Record<string, string> = {
  druhohoryCzech: "dino", rim: "column", stredovek: "wizard", budoucnost: "rocket", atlantis: "wave", bublina: "bubble",
  kofein: "coffee", chaos: "spiral", hruza: "skull", pizza: "pizza", kachny: "duck", solarni: "bolt",
  smysl: "hole", kachny2: "duck", teleport: "sparkle", kryo: "ice", powerpoint: "chart", scroll: "phone",
  zalozky: "rainbow", oprava: "wrench", inbox: "mail", motylek: "butterfly", singularita: "robot", nesmrtelnost: "sleep",
  kachny3: "duck", pondeli: "mirror", ticho: "mute", vecnost: "infinity", perlivka: "bubble", pravda: "clock",
};

export function PixelIcon({ optionId, size = 46 }: { optionId: string; size?: number }) {
  const name = ICON_FOR[optionId];
  const def = name ? ICONS[name] : null;
  if (!def) return null;
  const h = def.rows.length;
  const w = Math.max(...def.rows.map((r) => r.length));
  const cells: React.ReactNode[] = [];
  def.rows.forEach((row, y) => {
    for (let x = 0; x < row.length; x++) {
      const ch = row[x] as keyof typeof P;
      const fill = P[ch];
      if (fill) cells.push(<rect key={`${x}-${y}`} x={x} y={y} width={1.03} height={1.03} fill={fill} />);
    }
  });
  return (
    <svg width={size} height={(size * h) / w} viewBox={`0 0 ${w} ${h}`} shapeRendering="crispEdges" style={{ imageRendering: "pixelated", display: "block", filter: "drop-shadow(0 2px 2px rgba(0,0,0,0.35))" }}>
      {cells}
    </svg>
  );
}
